# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x8badd5256A22f3452AFbFEeC3a3CAF3F98173c25"
    chainName: base
    connections:
      - token: ethereum|pulsechain|0xCC89D8bEdfb39170fA74bcf1D28C9e399b82CCb2
    decimals: 18
    name: Incentive
    standard: EvmHypSynthetic
    symbol: INC
  - addressOrDenom: "0xCC89D8bEdfb39170fA74bcf1D28C9e399b82CCb2"
    chainName: pulsechain
    collateralAddressOrDenom: "0x2fa878Ab3F87CC1C9737Fc071108F904c0B0C95d"
    connections:
      - token: ethereum|base|0x8badd5256A22f3452AFbFEeC3a3CAF3F98173c25
    decimals: 18
    name: Incentive
    standard: EvmHypCollateral
    symbol: INC
